server:
  port: 10010
  servlet:
    context-path: /
  undertow:
    io-threads: 4
    worker-threads: 32
    buffer-size: 1024
    direct-buffers: true
logging:
  config: classpath:log4j2.xml
# do not change those config, unless you know what are u doing.
spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static
  aop:
    auto: true
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size:  20MB
  security:
    white-list:
      - /
      - /auth/**
      - /js/**
      - /css/**
      - /img/**
      - /fonts/**
      - /favicon.ico
      - /online/**
    auth0:
      public-key: 'ilis2.authorization.dlfjgdkfg832423j4.s.df98sdf'
      # minutes
      expires-at: 120
mybatis-plus:
  configuration:
    cache-enabled: false
    default-executor-type: reuse
    jdbc-type-for-null: 'null'
    lazy-loading-enabled: true
    local-cache-scope: session
    map-underscore-to-camel-case: true
    default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
  mapper-locations: classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: assign_id
      table-prefix: t_
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy:
      update-strategy: not_null
      select-strategy: not_empty
    banner: false
    super-mapper-class: com.baomidou.mybatisplus.core.mapper.BaseMapper
  type-enums-package: cn.hitek.authorization.ilis2.common.enums
  type-aliases-package:
  type-handlers-package:
---
spring:
  profiles: dev
  datasource:
    host: 127.0.0.1
    port: 3306
    url: jdbc:p6spy:mysql://127.0.0.1:3306/auth01?characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 4
      max-lifetime: 80000
      idle-timeout: 60000
      connection-timeout: 20000
      minimum-idle: 1
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 1
---
spring:
  profiles: test
  datasource:
    host: 192.168.2.3
    port: 3306
    url: jdbc:p6spy:mysql://192.168.2.3:3306/auth01?characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 4
      max-lifetime: 80000
      idle-timeout: 60000
      connection-timeout: 20000
      minimum-idle: 1
  redis:
    port: 6379
    host: 192.168.2.3
    password:
    database: 1
---
spring:
  profiles: prod
  datasource:
    host: 127.0.0.1
    port: 3306
    url: jdbc:mysql://127.0.0.1:3306/auth01?characterEncoding=utf8&serverTimezone=CTT&useSSL=false
    username: root
    password: hitek@aliyun1998
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 4
      max-lifetime: 80000
      idle-timeout: 60000
      connection-timeout: 20000
      minimum-idle: 1
  redis:
    port: 6379
    host: 127.0.0.1
    password:
    database: 4
